### ISSUE TITLE
【Chinese】This is a title for a Chinese test

### ISSUE THREAD

**Issue by cubxxw** [kubecub/kubecub#10]
要将已知的GitHub用户 kubbot 作为您的GitHub Actions机器人，请按照以下步骤操作：
1. 在GitHub上创建一个新的个人访问令牌，该令牌需要具有repo范围的权限。
2. 在您的GitHub存储库中创建一个名为 .github/workflows/main.yml 的新文件。
3. 将以下代码复制并粘贴到 main.yml 文件中：
```yaml
name: My Workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run a script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python my_script.py
```
4. 将 env 部分中的 GITHUB_TOKEN 更改为您在第1步中创建的个人访问令牌。
5. 将 my_script.py 更改为您要运行的脚本文件名。
6. 在您的GitHub存储库中创建一个名为 .github/workflows/kubbot.yml 的新文件。
7. 将以下代码复制并粘贴到 kubbot.yml 文件中：
```yaml
name: Kubbot Workflow
on:
  issue_comment:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Kubbot
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python kubbot.py
```
8. 将 kubbot.py 更改为您要运行的Kubbot脚本文件名。
9. 提交并推送这两个新文件到您的GitHub存储库中。
10. 现在，您的GitHub Actions机器人应该已经成功更改为已知的GitHub用户 kubbot。

**Comment by kubbot** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
To use the known GitHub user kubbot as your GitHub Actions bot, follow these steps:
1. Create a new personal access token on GitHub that needs to have repo-scoped permissions.
2. Create a new file called .github/workflows/main.yml in your GitHub repository.
3. Copy and paste the following code into the main.yml file:
```yaml
name: My Workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run a script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python my_script.py
```
4. Change GITHUB_TOKEN in the env section to the personal access token you created in step 1.
5. Change my_script.py to the script file name you want to run.
6. Create a new file called .github/workflows/kubbot.yml in your GitHub repository.
7. Copy and paste the following code into the kubbot.yml file:
```yaml
name: Kubbot Workflow
on:
  issue_comment:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Kubbot
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run:python kubbot.py
```
8. Change kubbot.py to the filename of the Kubbot script you want to run.
9. Commit and push the two new files to your GitHub repository.
10. Your GitHub Actions bot should now have successfully changed to the known GitHub user kubbot.
