### ISSUE TITLE
Chinese test

### ISSUE THREAD

**Issue by cubxxw** [kubecub/kubecub#6]
要在GitHub Actions中为issue打标签，您可以使用GitHub提供的[REST API](https://docs.github.com/en/rest)。以下是一个简单的示例，演示如何使用GitHub Actions为issue打标签：

```yaml
name: Add label to issue
on:
  issues:
    types: [opened]

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add label
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = context.payload.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const octokit = new github.GitHub(process.env.GITHUB_TOKEN);
            octokit.issues.addLabels({
              owner,
              repo,
              issue_number,
              labels: ['bug']
            });
```
在这个示例中，我们使用了`actions/github-script`操作来调用GitHub REST API。我们在`with`字段中提供了GitHub令牌和JavaScript脚本。在脚本中，我们首先获取issue的编号、所有者和存储库名称。然后，我们使用`octokit.issues.addLabels`方法为issue添加标签。在这个示例中，我们将标签设置为“bug”，但您可以根据需要更改它。
请注意，在上面的示例中，我们使用了`${{ secrets.GITHUB_TOKEN }}`作为GitHub令牌。这是一个特殊的令牌，它允许您在GitHub Actions中调用GitHub REST API。如果您需要使用其他令牌，请确保将其存储在GitHub存储库的secrets中，并将其作为环境变量传递给您的操作。

**Comment by kubbot** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
To tag an issue in GitHub Actions, you can use the [REST API](https://docs.github.com/en/rest) provided by GitHub. Here's a simple example of how to tag an issue using GitHub Actions:

```yaml
name: Add label to issue
on:
  issues:
    types: [opened]

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add label
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = context.payload.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const octokit = new github.GitHub(process.env.GITHUB_TOKEN);
            octokit.issues.addLabels({
              owner,
              repo,
              issue_number,
              labels: ['bug']
            });
```
In this example, we use the `actions/github-script` action to call the GitHub REST API. We provide the GitHub token and the JavaScript script in the `with` field. In the script, we first get the issue's number, owner and repository name. Then, we use the `octokit.issues.addLabels` method to add labels to the issue. In this example we set the label to "bug", but you can change it if you want.
Note that in the example above we used `${{ secrets.GITHUB_TOKEN }}` as the GitHub token. This is a special token that allows you to call the GitHub REST API in GitHub Actions. If you need to use a different token, make sure to store it in secrets in your GitHub repository and pass it to your action as an environment variable.
